version: '3.3'

services:  
    frontend:
        image: corrykalam/jenkins-frontend-example:dev
        container_name: frontend-vue
        ports:
            - 8080:8080
            - 80:80
        environment:
            - VUE_APP_BASE_URL=http://34.201.252.160/v1   
networks:
    default:
        external:
            name: backend_deploy